version: '3'

services:
  django:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: django-container
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend/crm
      dockerfile: Dockerfile
    container_name: vue-container
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend/crm:/app

  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
