# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Start the app
CMD ["npm", "run", "serve"]
